### ISSUE TITLE
Add option to enter manual location for map rather than using your current location

### ISSUE THREAD

**Issue by RajChaudhry** [codeforboston/communityconnect#327] opened 2019-06-19 14:31 UTC
Currently, our app only utilizes the location of the user when fetching nearby resources in the /:resource page. Some SW's indicated that they would like to search for resources close to their client's house. A good first step then would be to add functionality to add in specific addresses into the map on the client view (/:resource) and from there we can work further on it by adding radius filters.

**Comment by ndesai06** [comment] 2019-06-21 16:29
Closed #211

**Comment by galiat** [comment] 2019-10-15 23:38
Closing because this is a duplicate of #400

**Closed by galiat** 2019-10-15 23:38 UTC
Labels: enhancement
